### ISSUE TITLE
After database catchup there is an empty shard 

### ISSUE THREAD

**Issue by agazso** [scalien/scaliendb#366]
/storage looks like this:

```
- shard 29521 (tableID = 28296) 
   track: 1
   size: 0
   isSplitable: T
   firstKey: T:0000102680663|
   lastKey: T:0000136699640|
   midpoint: (empty)
   logSegmentID: 257
   logCommandID: 1
    * memo chunk 1617
       state: 0 {0=Tree, 1=Serialized, 2=Unwritten, 3=Written}
       size: 0
       count: 0
       firstKey: 
       lastKey: 
       midpoint: 
       minLogSegmentID: 0
       maxLogSegmentID: 0
       maxLogCommandID: 0
```
